// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Xy77RTWvV36XcylNlQBgNEg6HUdFqIE',
    appId: '1:840869615041:web:7c22f33b926ff37d868b40',
    messagingSenderId: '840869615041',
    projectId: 'chatter-b95ca',
    authDomain: 'chatter-b95ca.firebaseapp.com',
    storageBucket: 'chatter-b95ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyViI-uXOkvy0u__JEfgOi2SX-NDcFTVo',
    appId: '1:840869615041:android:4808c36647faba3e868b40',
    messagingSenderId: '840869615041',
    projectId: 'chatter-b95ca',
    storageBucket: 'chatter-b95ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARl3iEwOXZh4hyxmrTadoNGSrKev7LdAw',
    appId: '1:840869615041:ios:ea4875a2edf0f47e868b40',
    messagingSenderId: '840869615041',
    projectId: 'chatter-b95ca',
    storageBucket: 'chatter-b95ca.firebasestorage.app',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARl3iEwOXZh4hyxmrTadoNGSrKev7LdAw',
    appId: '1:840869615041:ios:ea4875a2edf0f47e868b40',
    messagingSenderId: '840869615041',
    projectId: 'chatter-b95ca',
    storageBucket: 'chatter-b95ca.firebasestorage.app',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Xy77RTWvV36XcylNlQBgNEg6HUdFqIE',
    appId: '1:840869615041:web:4f5239deaf90189e868b40',
    messagingSenderId: '840869615041',
    projectId: 'chatter-b95ca',
    authDomain: 'chatter-b95ca.firebaseapp.com',
    storageBucket: 'chatter-b95ca.firebasestorage.app',
  );
}
